### ISSUE TITLE
Duration of audiostream is 0

### ISSUE THREAD

**Issue by duysqubix** [gopxl/beep#106]
i try to stream audio from the internet and it is playing nicely, but i can not calculate the duration of the stream (it's actually a podcast). I set up the playback like this:

`

    func playRemoteFile() {
	resp, err := http.Get("https://traffic.libsyn.com/wakingup/Making_Sense_156_Nicholas_Christakis.mp3")

	if err != nil {
		log.Fatal(err)
	}

	streamer, format, err := mp3.Decode(resp.Body)
	if err != nil {
		log.Fatal(err)
	}
	defer streamer.Close()

	speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/10))

	ctrlStreamer := &beep.Ctrl{Streamer: streamer, Paused: false}

	done := make(chan bool)
	speaker.Play(beep.Seq(ctrlStreamer, beep.Callback(func() {
		done <- true
	})))

	for {
		select {
		case <-done:
			return
		case <-time.After(time.Second):
			speaker.Lock()
			fmt.Printf("time elapsed: %d of %d\n", format.SampleRate.D(streamer.Position()), format.SampleRate.D(streamer.Len()))
			speaker.Unlock()
		}
	}

    }

`

streamer.Len() returns 0.
the response contains only the content length. Is it possible to somehow calculate the duration?

 Original issue: https://github.com/faiface/beep/issues/57

**Comment by MarkKremer** [comment]
Answered by faiface in the original issue
