### ISSUE TITLE
The vorbis decoder hangs on Decode()

### ISSUE THREAD

**Issue by duysqubix** [gopxl/beep#110]
If it helps, here's the file I'm trying to play: 
[oggfile.zip](https://github.com/faiface/beep/files/3052445/oggfile.zip)

MP3 files work fine with the same code.

 Original issue: https://github.com/faiface/beep/issues/52

**Comment by MarkKremer** [comment]
I get the following error:
```
ogg/vorbis: ogg: missing capture pattern
```

So I think the file is malformed.
