### ISSUE TITLE
How To Cross-fade

### ISSUE THREAD

**Issue by duysqubix** [gopxl/beep#112]
This looks like a great library for playing audio, very simple.
One feature that I don't see by looking through the code or docs is how to cross-fade.
I would like to create an app that plays a playlist, playlist can be modified on the fly.
I would like to cross-fade by x seconds.
Bonus points if we can remove silence or levels under x dB.
Is this possible?
If not, is this something that could be added?

 Original issue: https://github.com/faiface/beep/issues/44

**Comment by MarkKremer** [comment]
Cross-fading is underway. I've created a new issue to track removal of silence: #142
