### ISSUE TITLE
Add Volume Control for `speaker` Package

### ISSUE THREAD

**Issue by dwisiswant0** [gopxl/beep#129]
### Current Behavior

The [`speaker`](https://pkg.go.dev/github.com/gopxl/beep/speaker) package allows for playback of [`beep.Streamer`](https://pkg.go.dev/github.com/gopxl/beep#Streamer) values through physical speakers. However, it lacks a built-in mechanism for controlling the volume of the audio output.

### Desired Behavior

It would be beneficial to add a feature that allows users to control the volume of audio playback using the [`speaker`](https://pkg.go.dev/github.com/gopxl/beep/speaker) package. This can be achieved through the addition of volume control options in the API, giving users the ability to fine-tune audio volume as per their requirements. It's worth noting that although Beep provides [`effects.Volume`](https://pkg.go.dev/github.com/gopxl/beep/effects#Volume), it currently operates at the [`beep.Streamer`](https://pkg.go.dev/github.com/gopxl/beep#Streamer) level and not at the speaker level (for all [`beep.Streamer`](https://pkg.go.dev/github.com/gopxl/beep#Streamer)).

### Proposed Implementation

1. Introduce a new method or option to the `speaker` API, such as in the [`speaker.Init`](https://pkg.go.dev/github.com/gopxl/beep/speaker#Init), that allows users to set the desired volume level.
2. The volume control should accept a value or range, with 0 being mute and 100 _(or maximum supported)_ being the loudest.
3. Ensures that [`effects.Volume`](https://pkg.go.dev/github.com/gopxl/beep/effects#Volume) takes precedence over the volume initialized through the [`speaker`](https://pkg.go.dev/github.com/gopxl/beep/speaker). This ensures that each [`beep.Streamer`](https://pkg.go.dev/github.com/gopxl/beep#Streamer) retains control over setting its own volume, allowing for more fine-grained adjustments.

### Benefits:

1. Improved user experience by providing volume control for audio playback.
2. Enables a broader range of apps and use cases, allowing for dynamic and _on-the-fly_ adjustments to speaker volume. This versatility is particularly valuable for applications where real-time volume modifications are essential.

### Example Use Case

Here I'm tryna develop Apple Hearing's Background Sounds drop-in replacement.

https://github.com/gopxl/beep/assets/25837540/032efa9d-0096-4533-98ac-48d340c52b6f

There I have over 30+ sounds, and I'd prefer not to individually adjust the volume for each [`beep.Streamer`](https://pkg.go.dev/github.com/gopxl/beep#Streamer).

Thanks!

**Comment by MarkKremer** [comment]
Would your scenario be solved by chaining a mixer and volume node before the speaker?
```
         Streamer
             ↓
Streamer → Mixer → Volume → Speaker
             ↑
         Streamer
```
