### ISSUE TITLE
How to know the instant playback was started?

### ISSUE THREAD

**Issue by gregoryjjb** [gopxl/beep#135]
I know the buffers make it hard but even with a 10ms buffer I'm getting around 500ms of latency, which seems high, and which I have to manually bias around. What's the most reliable way to get the instant playback was started at? I'm reading song-length MP3s so loading the entire file into memory is not doable.

My setup matches the readme pretty closely:

```go
// Ideally this function doesn't return until the exact instant playback starts
func (ap *AudioPlayer) Play(path string) (time.Time, error) {
	f, err := os.Open(path)
	if err != nil {
		return time.Time{}, err
	}

	// Does this buffer anything or does it read straight from the disk
	// when I do speaker.Play()? Can I somehow make it buffer some
	// bytes, so playback starts faster?
	streamer, format, err := mp3.Decode(f)
	if err != nil {
		return time.Time{}, err
	}

	ap.format = format
	ap.streamer = streamer

	buff := time.Millisecond * 10
	speaker.Init(format.SampleRate, format.SampleRate.N(buff))

	speaker.Play(ap.streamer)

	// ...and time.Now() turns out to be 500ms off :(
	return time.Now(), nil
}
```

**Comment by MarkKremer** [comment]
The speaker had a bug in it that made one of its internal buffers 0.5sec long. Fixed in https://github.com/gopxl/beep/pull/134 and I just tagged it so if you upgrade to beep v1.3.0 you should have it.

**Comment by gregoryjjb** [comment]
Very nice! Latency in v1.3.0 seems to be much more consistent, I can bias by the same duration as the buffer and get good results. Thanks!
