### ISSUE TITLE
Oto context isn't being released.

### ISSUE THREAD

**Issue by punkscience** [gopxl/beep#143]
I am playing a series of tracks from the command line. While the first always plays perfectly find, the second and every subsequent track results in the following error:

failed to initialize speaker: oto: context is already created

It appears as though it has run out of resources until I restart. I tried doing a defer Close() on the speaker as well as manually closing it before my "play()" function returns but neither had an impact.

**Comment by MarkKremer** [comment]
Hi 👋

Initializing the speaker multiple times and fully closing the underlying context isn't supported. Oto has removed the close method on the context and I'm planning to remove it from Beep too. If you want to play different audio clips of different sample rates, the recommended usage is to use the resampler and set the speaker to a reasonable predefined sample rate.

I'm planning on adding a suspend/resume function, they could save some cpu resources but don't release the context still.

**Comment by punkscience** [comment]
Looks like I was using it improperly. Once I moved the initialization to only happen once at the beginning of the program andjust reused it to play subsequent files, it worked rather smoothly so far. Thanks!
