### ISSUE TITLE
Problem with beep.Resample, Song speeds up

### ISSUE THREAD

**Issue by nkalait** [gopxl/beep#146]
I am having a problem with resampling audio where when if I have already started playing one audio file and I want to stop the currently playing file and start playing another. The problem is the second audio file I play sounds speeded up.

The documentation says:
```go
func beep.Resample(quality int, old beep.SampleRate, new beep.SampleRate, s beep.Streamer)
```
and I did exactly that with the following code:

```go
resampled = beep.Resample(6, oldSampleRate, format.SampleRate, *streamer)
``` 
where `oldSample` is **48000** and `format.SampleRate` **44100**

When I run the code like shown above the second file plays at a higher speed and tone, but when I swap `oldSampleRate` and  `format.SampleRate` like shown below I get the expected result, ie, the second file plays at its normal rate

```go
resampled = beep.Resample(6, oldSampleRate, format.SampleRate, *streamer)
```

**Comment by nkalait** [comment]
Working example can be found here [https://github.com/nkalait/test_beep](url) 

There are two media fils in folder "audio books".  It should compile and run without any modifications. 
In main.go you can edit the variable **_rootPath_** to give the path of the audio books folder provided and then compile and run

**Comment by MarkKremer** [comment]
Hey, it looks like there might be a misunderstanding about how the resampler works. Just to clarify, the resampler is meant to convert the samplerate of the source streamer to a desired samplerate. The `old` samplerate should match that of streamer `s`, and the `new` samplerate should be the desired sample rate, which typically (and in your case as well) is the one the speaker was initialized with. The swapped example is the correct usage.

I noticed in your example that the `audioPanel`'s format gets updated with every song. Keep in mind that the speaker's sample rate cannot be changed, so the `new` sample rate shouldn't be updated either. You could store the sample rate of the first audiobook played for that purpose, or simply initialize the speaker with a predefined sample rate like 44100 or 44800 and use it as a constant.

Feel free to reach out if you have any questions or need further clarification.

**Comment by nkalait** [comment]
Thank you for your timely response, I'll make the necessary changes in my code and get back in touch if I run into more challenges

**Comment by nkalait** [comment]
### Thank you very much, 
all is well now, does exactly what it is supposed to. I'll close the issue now
