### ISSUE TITLE
mp4

### ISSUE THREAD

**Issue by oq-x** [gopxl/beep#159]
Is there a decoder for mp4 files

**Comment by MarkKremer** [comment]
There is no decoder for mp4 files. However, mp4 is a container format which can contain other audio formats like AAC and MP3. AAC we don't support, MP3 we do. So in the small chance you specifically have a mp4 file containing MP3 then you may be able to use another library to extract it and then pass it to beep.

**Comment by MarkKremer** [comment]
Related: https://github.com/gopxl/beep/issues/108
