### ISSUE TITLE
Add MIDI playback support

### ISSUE THREAD

**Issue by K4thos** [gopxl/beep#162]
For the [Ikemen GO](https://github.com/ikemen-engine/Ikemen-GO) engine, @samhocevar added support for MIDI playback via go-meltysynth. We would prefer not having to maintain our own fork if this feature (and some other bug fixes that our devs are preparing PRs for) will be merged. Are you interested in adding this feature to gopxl/beep?
https://github.com/ikemen-engine/beep/commit/3fba40ddabccb5ee619c6e746b28e2295e1b6468

**Comment by MarkKremer** [comment]
Looks promising! I'll be on holliday soon so I'll have a look in a week or 2.

**Comment by MarkKremer** [comment]
I've made a PR with your code & some of my changes in https://github.com/gopxl/beep/pull/167. Let me know what you think! My apologies for the wait.

It would be cool to include an example of it's usage in Beep. For that I need a sound font and a midi file. Do you happen to know some (preferably public domain) files that could inspire future Beep users?

**Comment by MarkKremer** [comment]
Do you want to be credited somewhere?

**Comment by K4thos** [comment]
Hey, please give credit only to @samhocevar.

The code looks great, thank you very much for adopting it. When it is merged, we will switch to gopxl/beep right away.

Regarding soundfonts, I'm personally using this one:
[SC55EmperorGrieferus](https://archive.org/details/SC55EmperorGrieferus)
But for free-to-use ones, this pack is good:
[sf2-soundfonts-free-use](https://archive.org/details/sf2-soundfonts-free-use)

As for public domain music, maybe some classical tracks?
[Midi World - Classical Tracks](https://www.midiworld.com/classic.htm)

**Comment by MarkKremer** [comment]
I'll make sure to include his name in the release notes!

**Comment by MarkKremer** [comment]
Merged & released!
