### ISSUE TITLE
Unable to build on linux cross-compilation

### ISSUE THREAD

**Issue by thrasher-** [gopxl/beep#164]
When attempting to build an app I get the following build error from otov3@v3.2.0

```
$ GOOS=linux go build
# github.com/ebitengine/oto/v3
..\..\..\..\..\pkg\mod\github.com\ebitengine\oto\v3@v3.2.0\context.go:38:11: undefined: context
..\..\..\..\..\pkg\mod\github.com\ebitengine\oto\v3@v3.2.0\context.go:100:21: undefined: newContext
```

**Comment by MarkKremer** [comment]
See https://github.com/ebitengine/oto?tab=readme-ov-file#crosscompiling

**Comment by thrasher-** [comment]
I've followed those instructions. In this case it's a Windows host targeting linux. Have filed it upstream instead and will follow it up with them.
