### ISSUE TITLE
module needs v2 support

### ISSUE THREAD

**Issue by Jesuszilla** [gopxl/beep#171]
I noticed the latest release is a v2.0.0 release which has issues with current go.mod setups (I can only seem to retrieve 1.4.1 as of this writing). I'm new to Golang and contributing to the IKEMEN-Go project where we plan to update beep in our project to the latest. However, I seem to get this error when trying to retrieve v2:

```
~/D/Ikemen-GO ❯❯❯ go get -u github.com/gopxl/beep@v2.0.0
go: github.com/gopxl/beep@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/gopxl/beep/v2")
```

I was given this link in the IKEMEN-Go Discord for context to the v2 modules problem and some solutions https://donatstudios.com/Go-v2-Modules 

Not sure which method this project would prefer doing!

**Comment by MarkKremer** [comment]
I've updated the module path to `github.com/gopxl/beep/v2`.

Running `go get -u github.com/gopxl/beep/v2` and updating all the import paths should work. If you run into more trouble let me know :)
