### ISSUE TITLE
go 1.18 module support

### ISSUE THREAD

**Issue by duysqubix** [gopxl/beep#23]
Add proper module support for go 1.18, otherwise things that require submodules (like generators, etc) will not be able to resolve properly in the build system.

 Original issue: https://github.com/faiface/beep/pull/149

**Comment by duysqubix** [comment]
Is this issue even relevant?

**Comment by MarkKremer** [comment]
I'm wondering about placing `.mod` files in the submodule folders and/or example folders.

I'm closing it until the additional dependencies in the root package cause problems. The Go version upgrade is otherwise done. :ok_hand:
