### ISSUE TITLE
100% CPU usage on LINUX

### ISSUE THREAD

**Issue by duysqubix** [gopxl/beep#33]
On Windows BEEP is wonderful. On LINUX, it plays very well, but just linking V1.1.0 or earlier) into GO program on SBCs for RASPBIAN or ARMBIAN OS gives 100% CPU even without playing MP3. 

 Original issue: https://github.com/faiface/beep/issues/131

**Comment by MarkKremer** [comment]
Closing because the issue is stale and doesn't have an example to reproduce.

Feel free to re-open.
