### ISSUE TITLE
Oto v2.0 has been release :)

### ISSUE THREAD

**Issue by duysqubix** [gopxl/beep#35]
Oto v2.0 was just released :) https://github.com/hajimehoshi/oto/releases/tag/v2.0.0

> * New APIs
>    - Accepting io.Reader instead of io.Writer to create a player
>    - Richer Player interface
> * New implementations
>    - Much more buffers to avoid clicking noises

This issue tracks the work to update beep to use the latest version of Oto, bring with it performance increases.

 Original issue: https://github.com/faiface/beep/issues/128

**Comment by MarkKremer** [comment]
Solved in #3
